version: '2'
services:
  postgis:
    image: postgis/postgis
    container_name: workshop_postgis
    ports:
      - '1032:5432'
    environment:
      POSTGRES_USER: testing
      POSTGRES_PASSWORD: '302010'
      POSTGRES_DB: nyc
    restart: always
    volumes:
      - './home/:/home/'
      - './postgres_data/:/var/lib/postgresql/data/'
  pgadmin4:
    image: dpage/pgadmin4
    container_name: workshop_pgadmin
    depends_on:
      - postgis
    ports:
      - '1080:80'
    environment:
        PGADMIN_DEFAULT_EMAIL: testing@testing.com
        PGADMIN_DEFAULT_PASSWORD: '302010'
    volumes:
      - './home/:/home/'
      - './pg_admin/:/var/lib/pgadmin/'
volumes:
  home: {}
  postgres_data: {}
  pg_admin: {}
